# Generated by Django 4.2.8 on 2024-07-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationemails',
            name='role',
            field=models.CharField(choices=[('driver', 'driver'), ('customer', 'customer')], default='customer', max_length=100),
        ),
    ]
