# Generated by Django 4.2.8 on 2024-07-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_invitationemails_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationemails',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitationemails',
            name='email',
            field=models.CharField(blank=True, max_length=225, null=True, unique=True),
        ),
    ]
