# Generated by Django 4.2.8 on 2024-07-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_invitationemails_is_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
