# Generated by Django 4.2.8 on 2024-07-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payments_is_paid_rideorder_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideorder',
            name='coordinates',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='rideorder',
            name='distance',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('in_progress', 'in_progress'), ('completed', 'completed')], default='pending', max_length=225),
        ),
    ]
