# Generated by Django 4.2.8 on 2024-07-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rideorder_coordinates_rideorder_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideorder',
            name='coordinates',
        ),
    ]
